import csv
from datetime import datetime
from pathlib import Path
from typing import Literal

from bonvoyage.models.trip_state import TripState, Attraction, Hostel


def export_csv(
    data: list[Attraction] | list[Hostel],
    output_type: Literal["attractions", "hostels"],
    session_id: str,
) -> str:
    """Write data to CSV and return the file path."""
    exports_dir = Path(__file__).parent.parent / "exports"
    exports_dir.mkdir(exist_ok=True)

    file_path = exports_dir / f"{session_id}_{output_type}.csv"

    if output_type == "attractions":
        fieldnames = ["Name", "Category", "Address", "Lat", "Lon", "Notes"]
        rows = [
            {
                "Name": a.name,
                "Category": "Attraction",
                "Address": a.address,
                "Lat": a.lat if a.lat is not None else "",
                "Lon": a.lon if a.lon is not None else "",
                "Notes": a.description,
            }
            for a in data
        ]
    else:
        fieldnames = ["Name", "Address", "Notes"]
        rows = [
            {
                "Name": h.name,
                "Address": h.address,
                "Notes": h.description,
            }
            for h in data
        ]

    with open(file_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    return str(file_path)


def generate_markdown_summary(state: TripState, export_dir: Path | None = None) -> str:
    """Generate trip_summary.md from TripState. Returns file path."""
    exports_dir = export_dir or Path(__file__).parent.parent / "exports"
    exports_dir.mkdir(exist_ok=True)

    file_path = exports_dir / f"{state.session_id}_trip_summary.md"

    attractions_csv = exports_dir / f"{state.session_id}_attractions.csv"
    hostels_csv = exports_dir / f"{state.session_id}_hostels.csv"

    lines = [
        f"# BonVoyage Trip Summary",
        f"",
        f"---",
        f"",
        f"## Trip Overview",
        f"",
        f"- **Destination:** {state.destination}",
        f"- **Duration:** {state.duration_days} days",
        f"- **Traveler Profile:** {state.user_profile or 'Not specified'}",
        f"- **Interests:** {', '.join(state.interests) or 'Not specified'}",
        f"- **Must-Visit:** {', '.join(state.must_visit) or 'None specified'}",
        f"",
        f"---",
        f"",
        f"## Selected Attractions",
        f"",
    ]

    for i, attraction in enumerate(state.selected_attractions, 1):
        lines += [
            f"### {i}. {attraction.name}",
            f"",
            f"{attraction.description}",
            f"",
            f"**Why selected:** {attraction.rationale}",
            f"",
            f"**Address:** {attraction.address or 'See Google Maps'}",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## Hostels",
        f"",
    ]

    for hostel in state.selected_hostels:
        lines += [
            f"### {hostel.name}",
            f"",
            f"{hostel.description}",
            f"",
            f"**Address:** {hostel.address or 'See Google Maps'}",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## Possible Discounts",
        f"",
        f"*These are suggestions based on web search — verify eligibility before your trip.*",
        f"",
    ]

    if state.discounts:
        for discount in state.discounts:
            lines += [
                f"### {discount.name}",
                f"",
                f"{discount.description}",
                f"",
                f"**Eligibility:** {discount.eligibility}",
                f"",
            ]
    else:
        lines.append("No specific discounts found for your profile.")
        lines.append("")

    lines += [
        f"---",
        f"",
        f"## Exported Files",
        f"",
        f"- `{attractions_csv.name}` — Import to Google My Maps for attraction pins",
        f"- `{hostels_csv.name}` — Import to Google My Maps for hostel pins",
        f"",
        f"---",
        f"",
        f"## How to Import to Google My Maps",
        f"",
        f"1. Go to [Google My Maps](https://www.google.com/maps/d/)",
        f"2. Click **Create a new map**",
        f"3. Click **Import** under the first untitled layer",
        f"4. Upload `{attractions_csv.name}` — select **Lat** and **Lon** as location columns, **Name** as the title",
        f"5. Click **Add layer** and repeat for `{hostels_csv.name}`",
        f"6. Rename layers to 'Attractions' and 'Hostels'",
        f"7. Share or use offline via the Google Maps app",
        f"",
        f"---",
        f"",
        f"*Generated by BonVoyage on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
    ]

    file_path.write_text("\n".join(lines), encoding="utf-8")
    return str(file_path)
